name: PR Checks

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    backend:
        name: Backend checkout
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

    frontend:
        name: Frontend checkout
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
